#!/bin/sh

# I received this script from someone else and don't know the original author.
# The same goes for the called scripts.

load="$(sb-cpu-load)"
temp="$(sb-cpu-temp)"
# mem="$(sb-mem)"

# echo "CPU: $load $temp"
# echo "$mem  $load  $temp"
echo " $load  $temp"
