#! /bin/bash

shopt -s extglob

rolling_text() {
    text=$1
    max_length=$2
    text_length=${#text}
    if [[ $text_length -ge $max_length ]]; then
        time=$(awk '{print int($1) + 1000}' /proc/uptime)
        time=$((time % max_length))
        text="${text} » ${text}"
        text=${text:time}
        text=${text::max_length}
        echo "$text"
    else
        echo "$text"
    fi
}

quodlibet_status=$(playerctl status --player quodlibet 2>/dev/null)

if [[ $quodlibet_status != "Paused" && $quodlibet_status != "No players found" ]]; then
	song_data=$(playerctl metadata --player quodlibet --format "{{artist}} - {{title}}" 2>/dev/null)
else
	if [ "$(playerctl status)" == "Paused" ]; then
		echo "~"
		exit 0
	fi
	song_data=$(playerctl metadata --format "{{artist}} - {{title}}" 2>/dev/null)
fi

artist=$(echo "${song_data}" | awk -F " - " '{print $1}' | awk '{$1=$1}1')
title=$(echo "${song_data}" | awk -F " - " '{print $2}' | awk '{$1=$1}1')
song_data="${artist:+${artist} - }${title}"

text_length=30

signal_pattern="Signal?( ([0-9]))"
signal_pattern="Signal?()"

if [[ -z $song_data || ${title} == "YouTube Music" || ${title} =~ $signal_pattern ]]; then
    echo "~"
else
    song_data=$(rolling_text "$song_data" "$text_length")
    echo "$song_data"
fi
