#!/bin/sh

connections=$(ip a | grep enp0s20f | grep inet | wc -l)
wifi_connections=$(ip a | grep wlp2s0 | grep inet | wc -l)
if [ $connections -eq 1 ] ; then
    # echo "NET: On"
    echo ""
elif [ $wifi_connections ] ; then
    echo "睊"
else
    # echo "NET: Off"
    echo ""
fi

