#!/bin/sh

# I received this script from someone else and don't know the original author.
# The same goes for the called scripts.

load="$(sb-cpu-load)"
temp="$(sb-cpu-temp)"
mem=$(free -b | awk '/^Mem:/ { print $3 }')

if [ "$mem" -gt $((3*1073741824)) ]; then
    mem=$(echo "$mem" | numfmt --to iec)
    mem=" ${mem}"
else
    mem=""
fi



if [ "$load" -gt 10 ]; then
    load=" ${load}%"
else
    load=""
fi



if [ "$temp" -gt 55 ]; then
    temp=" ${temp}°C"
else
    temp=""
fi

echo "$mem $load $temp" | xargs echo -n
