#!/bin/bash

default="\x0b"
purple="\x11"
green="\x10"
yellow="\x0f"
orange="\x0e"
red="\x0d"

load() {
    read -r _ a b c previdle rest </proc/stat
    prevtotal=$((a + b + c + previdle))
    sleep 0.5
    read -r _ a b c idle rest </proc/stat
    total=$((a + b + c + idle))

    load=$((100 * ((total - prevtotal) - (idle - previdle)) / (total - prevtotal)))
    echo $load | numfmt --format "%2.0f"
}

temp() {
    temp=$(sensors | awk '/Core 0/ { print $3 }' | sed "s/+//;s/\.[0-9]//;s/°C//")
    echo "$temp"
}

mem() {
    free -b | awk '/^Mem:/ { print $3 }'
}

load="$(load)"
temp="$(temp)"
mem="$(mem)"

one_gigabyte=1073741824

if [ "$mem" -gt $((2 * one_gigabyte)) ]; then
	if [ "$mem" -lt $((3 * one_gigabyte)) ]; then
		color="${default}"
	elif [ "$mem" -lt $((4 * one_gigabyte)) ]; then
		color="${purple}"
	elif [ "$mem" -lt $((5 * one_gigabyte)) ]; then
		color="${yellow}"
	elif [ "$mem" -lt $((6 * one_gigabyte)) ]; then
		color="${orange}"
    else
		color="${red}"
	fi
	mem=$(echo "$mem" | numfmt --to iec)
	mem="${color} ${mem}${default}"
else
	mem=""
fi

if [ "$load" -gt 5 ]; then
	if [ "$load" -lt 15 ]; then
		color="${default}"
	elif [ "$load" -lt 20 ]; then
		color="${purple}"
	elif [ "$load" -lt 40 ]; then
		color="${green}"
	elif [ "$load" -lt 60 ]; then
		color="${yellow}"
	elif [ "$load" -lt 80 ]; then
		color="${orange}"
    else
		color="${red}"
	fi
	load="${color} ${load}%${default}"
else
	load=""
fi

if [ "$temp" -gt 50 ]; then
	if [ "$temp" -lt 60 ]; then
		color="${default}"
	elif [ "$temp" -lt 65 ]; then
		color="${purple}"
	elif [ "$temp" -lt 75 ]; then
		color="${yellow}"
	elif [ "$temp" -lt 85 ]; then
		color="${orange}"
    else
		color="${red}"
	fi
	temp="${color} ${temp}°C${default}"
else
	temp=""
fi

printf '%b' "$mem $load $temp" | xargs echo -n
