#! /bin/bash

n_tasks=$(task +TODAY stats | grep "Pending" | awk '{print $2}')
n_overdue_tasks=$(task 'due < today' stats | grep "Pending" | awk '{print $2}')
n_tasks_done_today=$(task +COMPLETED modified:today stats | grep "Completed" | awk '{print $2}')

# echo "Tasks: ${n_tasks}"
# echo " ${n_tasks}"
if [ "$n_overdue_tasks" -gt 0 ]; then
    echo " ${n_tasks} 鬒 ${n_overdue_tasks}  $n_tasks_done_today"
else
    echo " ${n_tasks}  $n_tasks_done_today"
fi
# echo "陼 ${n_tasks}"
