#! /bin/bash

today_start=$(date --date="4 hours ago" "+%Y-%m-%dT04:00:00")
tomorrow_start=$(date --date="+20 hours" "+%Y-%m-%dT04:00:00")

n_tasks=$(task due.before:"$tomorrow_start" and due.after:"$today_start" -OVERDUE stats | grep "Pending" | awk '{print $2}')
n_overdue_tasks=$(task +OVERDUE stats | grep "Pending" | awk '{print $2}')
n_tasks_done_today=$(task +COMPLETED modified.after:"$today_start" stats | grep "Completed" | awk '{print $2}')

# echo "Tasks: ${n_tasks}"
# echo " ${n_tasks}"
if [ "$n_overdue_tasks" -gt 0 ]; then
    echo -e " ${n_tasks} \x0e鬒 ${n_overdue_tasks}\x0b  $n_tasks_done_today"
else
    echo " ${n_tasks}  $n_tasks_done_today"
fi
# echo "陼 ${n_tasks}"
