#!/bin/sh

if pactl list | grep bluez_output >/dev/null; then
    pactl get-sink-volume @DEFAULT_SINK@ | sed -nr '1 s/[^/]*\/\s*([0-9]+%).*/󰥰 \1/ p'
else
    pactl get-sink-volume @DEFAULT_SINK@ | sed -nr '1 s/[^/]*\/\s*([0-9]+%).*/ \1/ p'
fi
