#! /bin/bash

# Change the coordinates in the url if you want weather data for another
# location.
weather_data_lund=$(curl -A "sb-weather/0.1" -s "https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=55.7179&lon=13.20798")
today_weather=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[0].data.next_6_hours.summary.symbol_code')
today_temp=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[0].data.instant.details.air_temperature')
# today_time=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[0].time')
# tomorrow_weather=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[24].data.next_12_hours.summary.symbol_code')
# tomorrow_time=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[24].time')
# tomorrow_temp=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[24].data.instant.details.air_temperature')

round() {
	round_n=$(echo "$1" | awk '{print ($0>0)?(($0-int($0)<0.5)?int($0):(int($0)+1)):((int($0)-$0<0.5)?int($0):int($0)-1)}')
	if [ $((round_n)) -lt 0 ]; then
		echo -n ""
	else
		echo -n "+"
	fi
	echo -n "${round_n}°C "
}

declare -A symbol_map

# Map of weather icon names and human readable expressions
symbol_map["cloudy"]=""
symbol_map["clearsky_day"]=""
symbol_map["lightsleet"]=""
symbol_map["lightrain"]=""
symbol_map["fog"]=""
symbol_map["clearsky_night"]=""
symbol_map["fair_night"]=""
symbol_map["partlycloudy_night"]=""
symbol_map["partlycloudy_day"]=""
symbol_map["snow"]=""
symbol_map["sleet"]=""

human_readable() {
	if [[ -v symbol_map[$1] ]]; then
		echo ${symbol_map[$1]}
	else
		echo "$1"
	fi
}

# echo "Temperature the following 6 hours:"
round "$today_temp"
# echo "Weather the following 6 hours:"
human_readable "$today_weather"
