#! /bin/bash

weather_data_lund=$(curl -A "sb-weather/0.1" -s "https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=55.7179&lon=13.20798")
today_weather=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[0].data.next_6_hours.summary.symbol_code')
today_temp=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[0].data.instant.details.air_temperature')
today_time=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[0].time')
tomorrow_weather=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[24].data.next_12_hours.summary.symbol_code')
tomorrow_time=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[24].time')
tomorrow_temp=$(echo "${weather_data_lund}" | jq -r '.properties.timeseries[24].data.instant.details.air_temperature')
echo "$weather_data_lund" | gron | head -n 50
# echo "$weather_data_lund"

# if [ $today_temp > 0 ]; then
#     $today_temp = $(echo $today_temp | awk '{print int($1)+0.5}')
#     echo $today_temp
# else
#     $today_temp = $(echo $today_temp | awk '{print int($1)-0.5}')
#     echo $today_temp
# fi
#

round () {
    echo $1 | awk '{print ($0>0)?(($0-int($0)<0.5)?int($0):(int($0)+1)):((int($0)-$0<0.5)?int($0):int($0)-1)}'
}

# if [ $tomorrow_temp > 0 ]; then
#     $tomorrow_temp = $(echo $tomorrow_temp | awk '{print int($1)+0.5}')
#     echo $tomorrow_temp
# else
#     $tomorrow_temp = $(echo $tomorrow_temp | awk '{print int($1)-0.5}')
#     echo $tomorrow_temp
# fi
#

declare -A symbol_map

# Map of weather icon names and human readable expressions
symbol_map["cloudy"]="Cloudy"
symbol_map["clearsky_day"]="Clear sky"

human_readable() {
    if [ -v symbol_map[$1] ] ; then
        echo ${symbol_map[$1]}
    else
        echo $1
    fi
}

echo ""
echo "The following data is for: ${today_time}"
echo "Temperature the following 6 hours:"
round $today_temp
echo "Weather the following 6 hours:"
human_readable $today_weather

echo ""
echo "The following data is for: ${tomorrow_time}"
echo $tomorrow_time | xargs date +%Y-%m-%d -d
echo "Temperature tomorrow:"
round $tomorrow_temp
echo "Weather tomorrow:"
human_readable $tomorrow_weather
